### ISSUE TITLE
Project is no longer being worked on

### ISSUE THREAD

**Issue by fartboxmk2** [flathub/com.beakerbrowser.Beaker#12]
The creator of beaker is no longer working on it: https://github.com/beakerbrowser/beaker/discussions/1944#discussioncomment-1308779

And this flatpak has been outdated for a while, it might be a good idea to [End of life](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life) it so people don't unknowingly install an abandoned web browser.

**Comment by G-Ray** [comment]
Thank you @fartboxmk2.
I pushed https://github.com/flathub/com.beakerbrowser.Beaker/commit/149c34f68e8bcc664852111945202b55691d9896.
